_target_: src.models.DAG_GCN.DAG_GCN

encoder:
  _target_: src.models.components.DAG_GCN_components.DAG_GCN_Encoder
  in_channels: 1 # feature size
  H1: 8
  H2: 64
  H3: 8
  out_channels: 1

decoder:
  _target_: src.models.components.DAG_GCN_components.DAG_GCN_Decoder
  in_channels: 1
  H3: 8
  H2: 64
  H1: 8
  out_channels: 1 # feature size

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  weight_decay: 0.0

# scheduler:
#   _target_: torch.optim.lr_scheduler.StepLR
#   _partial_: true
#   step_size: 100
#   gamma: 1.0

num_features: 11
batch_size: 512
graph_threshold: 0.3

plot_every: 10

gt_path: ${paths.data_dir}/sachs_dataset/sachs_gt.csv
raw_path: ${paths.data_dir}/sachs_dataset/raw/sachs.csv