_target_: src.models.DAG_GCN.DAG_GCN

activation: torch.nn.LeakyReLU
batch_norm: true
init: true
encoder:
  _target_: src.models.components.DAG_GCN_components.DAG_GCN_Encoder
  in_channels: 1 # feature size
  H1: 64
  H2: 64
  H3: 64
  out_channels: 1
  activation:
    _target_: ${model.activation}
  batch_norm: ${model.batch_norm}
  num_features: ${model.num_features}
  init: ${model.init}
decoder:
  _target_: src.models.components.DAG_GCN_components.DAG_GCN_Decoder
  in_channels: 1
  H3: 64
  H2: 64
  H1: 64
  out_channels: 1 # feature size
  activation:
    _target_: ${model.activation}
  batch_norm: ${model.batch_norm}
  num_features: ${model.num_features}
  init: ${model.init}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  weight_decay: 0.0

# scheduler:
#   _target_: torch.optim.lr_scheduler.StepLR
#   _partial_: true
#   step_size: 100
#   gamma: 1.0

num_features: 11
batch_size: 512

lambda_A: 0.0
c_A: 1
eta: 10
gamma: 0.25
graph_threshold: 0.3

adj_high: 0.1
adj_low: -0.1

plot_every: 10

gt_path: ${paths.data_dir}/sachs_dataset/sachs_gt_bn.csv
raw_path: ${paths.data_dir}/sachs_dataset/raw/sachs.csv