_target_: src.models.GAE_torch.CAE

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 3e-4
  weight_decay: 0.0
  
d: 11
n_dim: 1
n_hid: 16
n_latent: 8
n_layers: 5
lambda_sparsity: 1.0
psp: True

gt_path: ${paths.data_dir}/sachs_dataset/sachs_gt.csv