_target_: src.models.GAE_torch.CAE

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  weight_decay: 0.0
  
d: 11
n_dim: 1
n_hid: 4
n_latent: 4
n_layers: 3
lambda_sparsity: 1.0
psp: False

gt_path: ${paths.data_dir}/sachs_dataset/sachs_gt.csv