wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.13
    start_time: 1658699420
    t:
      1:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      - 53
      - 55
      - 77
      3:
      - 2
      - 7
      - 23
      4: 3.9.13
      5: 0.12.21
      8:
      - 5
callbacks/early_stopping/_target_:
  desc: null
  value: pytorch_lightning.callbacks.EarlyStopping
callbacks/early_stopping/check_finite:
  desc: null
  value: true
callbacks/early_stopping/check_on_train_epoch_end:
  desc: null
  value: None
callbacks/early_stopping/divergence_threshold:
  desc: null
  value: None
callbacks/early_stopping/min_delta:
  desc: null
  value: 0.0
callbacks/early_stopping/mode:
  desc: null
  value: max
callbacks/early_stopping/monitor:
  desc: null
  value: val/acc
callbacks/early_stopping/patience:
  desc: null
  value: 100
callbacks/early_stopping/stopping_threshold:
  desc: null
  value: None
callbacks/early_stopping/strict:
  desc: null
  value: true
callbacks/early_stopping/verbose:
  desc: null
  value: false
callbacks/model_checkpoint/_target_:
  desc: null
  value: pytorch_lightning.callbacks.ModelCheckpoint
callbacks/model_checkpoint/auto_insert_metric_name:
  desc: null
  value: false
callbacks/model_checkpoint/dirpath:
  desc: null
  value: /workspace/my_DAG_GraphVAE/lightning-hydra-template/logs/train/runs/2022-07-24_23-50-12/checkpoints
callbacks/model_checkpoint/every_n_epochs:
  desc: null
  value: None
callbacks/model_checkpoint/every_n_train_steps:
  desc: null
  value: None
callbacks/model_checkpoint/filename:
  desc: null
  value: epoch_{epoch:03d}
callbacks/model_checkpoint/mode:
  desc: null
  value: max
callbacks/model_checkpoint/monitor:
  desc: null
  value: val/acc
callbacks/model_checkpoint/save_last:
  desc: null
  value: true
callbacks/model_checkpoint/save_on_train_epoch_end:
  desc: null
  value: None
callbacks/model_checkpoint/save_top_k:
  desc: null
  value: 1
callbacks/model_checkpoint/save_weights_only:
  desc: null
  value: false
callbacks/model_checkpoint/train_time_interval:
  desc: null
  value: None
callbacks/model_checkpoint/verbose:
  desc: null
  value: false
callbacks/model_summary/_target_:
  desc: null
  value: pytorch_lightning.callbacks.RichModelSummary
callbacks/model_summary/max_depth:
  desc: null
  value: -1
callbacks/rich_progress_bar/_target_:
  desc: null
  value: pytorch_lightning.callbacks.RichProgressBar
ckpt_path:
  desc: null
  value: None
datamodule/_target_:
  desc: null
  value: src.datamodules.sachs_datamodule.SachsDataModule
datamodule/batch_size:
  desc: null
  value: 16
datamodule/data:
  desc: null
  value: /workspace/my_DAG_GraphVAE/lightning-hydra-template/data//sachs_dataset
extras/enforce_tags:
  desc: null
  value: true
extras/ignore_warnings:
  desc: null
  value: false
extras/print_config:
  desc: null
  value: true
model/_target_:
  desc: null
  value: src.models.DAG_GNN_module.DAG_GNN
model/optimizer/_partial_:
  desc: null
  value: true
model/optimizer/_target_:
  desc: null
  value: torch.optim.Adam
model/optimizer/lr:
  desc: null
  value: 0.001
model/optimizer/weight_decay:
  desc: null
  value: 0.0
model/params/non_trainable:
  desc: null
  value: 0
model/params/total:
  desc: null
  value: 4396
model/params/trainable:
  desc: null
  value: 4396
seed:
  desc: null
  value: 42
tags:
  desc: null
  value:
  - dev
task_name:
  desc: null
  value: train
trainer/_target_:
  desc: null
  value: pytorch_lightning.Trainer
trainer/accelerator:
  desc: null
  value: cpu
trainer/default_root_dir:
  desc: null
  value: /workspace/my_DAG_GraphVAE/lightning-hydra-template/logs/train/runs/2022-07-24_23-50-12
trainer/deterministic:
  desc: null
  value: false
trainer/devices:
  desc: null
  value: 1
trainer/max_epochs:
  desc: null
  value: 10
trainer/min_epochs:
  desc: null
  value: 1
